table Returns
	lineageTag: 72908ca5-bf5d-4327-b9c8-814f10dbfefd

	column 'Order ID'
		dataType: int64
		formatString: 0
		lineageTag: 6266646e-baf2-490d-bf93-fdc5595ea6a5
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 09112123-03d4-4882-ab39-385081056a7a
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition Returns = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\sriram.pippalla\Documents\PracticeGit\PracticePBI\SuperStoreUS-2015.xlsx"), null, true),
				    Returns_Sheet = Source{[Item="Returns",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Returns_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order ID", Int64.Type}, {"Status", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

