table Orders
	lineageTag: 55bf70f1-7e11-472f-8edf-123de905367e

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: e778cacf-dbb3-400a-8b67-2ef2353aeeb5
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order Priority'
		dataType: string
		lineageTag: fabee526-6876-4712-a961-65eaded627a1
		summarizeBy: none
		sourceColumn: Order Priority

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: b50541fe-03dc-47a0-ad1b-1d14d3003ca0
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Price'
		dataType: double
		lineageTag: c7592e27-292f-4cd0-8411-bc6ff379dc9a
		summarizeBy: sum
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Shipping Cost'
		dataType: double
		lineageTag: 8b5effc6-245c-4865-a85f-1be36b0c30ca
		summarizeBy: sum
		sourceColumn: Shipping Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Customer ID'
		dataType: int64
		formatString: 0
		lineageTag: c94580ea-8b03-4256-b404-958838419a76
		summarizeBy: count
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: ec08f3b7-6826-47f2-937e-b1f409eb49c1
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: d800a5d9-b338-4920-ae2f-e3138130026e
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment'
		dataType: string
		lineageTag: c319c402-b343-4ad0-8e0f-faf5b1db4714
		summarizeBy: none
		sourceColumn: Customer Segment

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		lineageTag: 93712aae-bfb1-4c66-a538-e3f4c300cf83
		summarizeBy: none
		sourceColumn: Product Category

		annotation SummarizationSetBy = Automatic

	column 'Product Sub-Category'
		dataType: string
		lineageTag: 057e7d40-b645-40f0-8ac8-e6c73e88ac00
		summarizeBy: none
		sourceColumn: Product Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Container'
		dataType: string
		lineageTag: cc89ecf3-52be-49a5-8bb6-06ac4704f08e
		summarizeBy: none
		sourceColumn: Product Container

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: be80907f-4a32-4b98-a5da-d17d9793a9e4
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column 'Product Base Margin'
		dataType: double
		lineageTag: 8f3d924a-4090-444e-a718-2ae946670e5e
		summarizeBy: sum
		sourceColumn: Product Base Margin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Country
		dataType: string
		lineageTag: cabb8313-20ed-4e70-9560-138b3a6807bf
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: dd2bba16-1919-4aa3-bf86-8eec40d75ac4
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'State or Province'
		dataType: string
		lineageTag: 37f41059-b3a4-4199-a4da-0be9cb875c52
		summarizeBy: none
		sourceColumn: State or Province

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 8da9b9ac-27db-40ff-bb49-233fd8c23798
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: e4b9cf88-c960-45ea-b705-966b5470a1e9
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1c28b944-cc85-42c4-8ecf-ea70c7e93eeb
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 16b35aae-fcdc-408c-84a1-a7e5c91f1473
			defaultHierarchy: LocalDateTable_966ea91a-e96c-4182-9919-35c56ba72c21.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2c3660a0-537e-4297-853c-993f3e0eacd1
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: f50d7630-2d9a-41fa-a4d8-608241957dc0
			defaultHierarchy: LocalDateTable_3bd57860-1306-4c53-b871-c55d5d1fdaa2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Profit
		dataType: double
		lineageTag: f1b5f8b2-d869-4b1a-8a93-52ba8799d2aa
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Quantity ordered new'
		dataType: int64
		formatString: 0
		lineageTag: 1212e29f-6336-4044-97aa-df48d8df6858
		summarizeBy: sum
		sourceColumn: Quantity ordered new

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: ff64e6bf-926d-43f9-b122-4790f15549b8
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order ID'
		dataType: int64
		formatString: 0
		lineageTag: af1e8461-62da-483e-934f-d90c8171c469
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column Column26
		dataType: string
		lineageTag: 69769d69-efce-4dce-aafe-697049781dfb
		summarizeBy: none
		sourceColumn: Column26

		annotation SummarizationSetBy = Automatic

	column Column27
		dataType: string
		lineageTag: 94d901d8-609b-4edd-9aab-2f2c00590e24
		summarizeBy: none
		sourceColumn: Column27

		annotation SummarizationSetBy = Automatic

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://impetusinfotech-my.sharepoint.com/personal/sriram_pippalla_impetus_com/Documents/SuperStoreUS-2015.xlsx"), null, true),
				    Orders_Sheet = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order Priority", type text}, {"Discount", type number}, {"Unit Price", type number}, {"Shipping Cost", type number}, {"Customer ID", Int64.Type}, {"Customer Name", type text}, {"Ship Mode", type text}, {"Customer Segment", type text}, {"Product Category", type text}, {"Product Sub-Category", type text}, {"Product Container", type text}, {"Product Name", type text}, {"Product Base Margin", type number}, {"Country", type text}, {"Region", type text}, {"State or Province", type text}, {"City", type text}, {"Postal Code", Int64.Type}, {"Order Date", type date}, {"Ship Date", type date}, {"Profit", type number}, {"Quantity ordered new", Int64.Type}, {"Sales", type number}, {"Order ID", Int64.Type}, {"Column26", type any}, {"Column27", type any}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

